services:
  scansnap:
    build: .
    image: ghcr.io/jollyjinx/scannerserver:latest
    container_name: scannerserver
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    network_mode: host
    environment:
      WEB_PORT: "80"
      TZ: "${TZ:-Europe/Berlin}"
    volumes:
      - ./scans:/scans
