services:
  scansnap:
    image: ghcr.io/jollyjinx/scannerserver:latest
    container_name: scannerserver
    hostname: scannerserver
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      WEB_PORT: "80"
      TZ: "${TZ:-Europe/Berlin}"
    networks:
      aservice1010:
        ipv4_address: ${NETWORK_PREFIX}.10.6
    mac_address: "da:e0:c0:24:d4:f8"
    volumes:
      - /home/ubuntu/plt/scans:/scans

networks:
  aservice1010:
    external: true
    name: plt_aservice1010
